name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive Function App files
        run: zip -r function.zip .
        working-directory: .

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ci-cd-8985513
          package: function.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
