name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./

    - name: Archive Function App files
      run: |
        zip -r functionapp.zip .
      working-directory: ./

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ci-cd-8985513                     # Replace with your Function App name
        package: functionapp.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
